language: cpp

compiler:
    - gcc

before_script:
    - mkdir build
    - cd build
    - cmake ..

script: make

# blocklist
branches:
  except:
  - experimental

# safelist
branches:
  only:
  - master