dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
      - curl
script:
  - export CC=/usr/bin/gcc-6
  - export CXX=/usr/bin/g++-6
  # Run your build commands next
  - git clone https://github.com/openssl/openssl.git
  - cd openssl
  - ./config no-shared
  - make -j9
  - sudo make install -j9
  - cd ..
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .

# blocklist
branches:
  except:

# safelist
branches:
  only:
  - master
