language: cpp
sudo: required
dist: trusty
compiler:
- clang
- gcc
matrix:
  include:
    - os: linux
          addons:
            apt:
              sources:
                - ubuntu-toolchain-r-test
              packages:
                - g++-7
          env:
            - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
          addons:
            apt:
              sources:
                - llvm-toolchain-trusty-5.0
              packages:
                - clang-5.0
          env:
            - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
    - eval "${MATRIX_EVAL}"
    - mkdir build
    - cd build
    - cmake ..

script: make -j9

# blocklist
branches:
  except:

# safelist
branches:
  only:
  - master
