language: cpp

compiler:
    - gcc

#before_script:
#    - mkdir build
#    - cd build
#    - cmake ..

script: ./installer.py compile

# blocklist
branches:
  except:

# safelist
branches:
  only:
  - master
