language: cpp
sudo: required
dist: trusty
compiler:
  - clang
addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
    packages:
      - clang-5.0

before_install:
    - eval "CC=clang-5.0 && CXX=clang++-5.0"
    - mkdir build
    - cd build
    - cmake ..

script: make -j9

# blocklist
branches:
  except:

# safelist
branches:
  only:
  - master
