dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6

script:
  - CORES=$(grep -c ^processor /proc/cpuinfo)
  - CXX=/usr/bin/g++-6 CC=/usr/bin/gcc-6 cmake -DBUILD_TESTING=TRUE .
  - make -j $CORES -l $CORES
  - make test

# safelist
branches:
  only:
  - master
