dist: xenial
sudo: true

language: cpp

compiler:
    - gcc
    - clang

before_script:
    - apt-get update && apt-get -y install build-essential cmake libssl-dev pkgconf
    - mkdir build
    - cd build
    - cmake ..

script: make

# blocklist
branches:
  except:
  - experimental

# safelist
branches:
  only:
  - master